### ISSUE TITLE
每日自动打卡不太好实现

### ISSUE THREAD

**Issue by nijunfeng234154** [InfinityWei/NUIST_HealthyReport_NEW#10]
ubuntu报错权限不足
作者大大能否给些详细操作说明

**Comment by InfinityWei** [comment]
项目本身是没问题的，一句权限不足我也不知道是哪里权限不足，你可以多试一试
我猜是配置Crontab时的权限不足，如果是这样的话，你的脚本需要chmod +x赋予可执行权限才可以正常调用
如果还搞不出来也可以使用已经配置好的GitHub Actions或者腾讯云函数（云函数的包已经在Release里面了）
手把手的说明目前不会写，因为担心会造成项目的更大范围扩散，这并不是一件好事
