### ISSUE TITLE
信息泄露

### ISSUE THREAD

**Issue by iamHuFei** [InfinityWei/NUIST_HealthyReport_NEW#15]
同学，你的账号密码在release的云函数main包泄露了，记得删

**Comment by InfinityWei** [comment]
感谢您的提醒，正在删除相关记录，不过我已经毕业，要这账号密码也没啥用了

**Comment by InfinityWei** [comment]
可以的，q1012871944

**Comment by iamHuFei** [comment]
> 可以加个好友吗，因为第一次用云函数，一直部署不成功 胡爽 ***@***.*** 南京信息工程大学 学生 19825061712 &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "InfinityWei/NUIST_HealthyReport_NEW" ***@***.***&gt;; 发送时间:&nbsp;2022年8月1日(星期一) 晚上11:55 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [InfinityWei/NUIST_HealthyReport_NEW] 信息泄露 (Issue #15) 感谢您的提醒，正在删除相关记录，不过我已经毕业，要这账号密码也没啥用了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
