### ISSUE TITLE
Could you give me more detail information of how to use it ?

### ISSUE THREAD

**Issue by TFboy1** [InfinityWei/NUIST_HealthyReport_NEW#17]
Your file report,py will close when clicked,and I can not see any more tips about whether I succeed or not ,can you give me more help ? thank you very much.

**Comment by InfinityWei** [comment]
Please read the README.md, there are some guidelines in it.

**Comment by TFboy1** [comment]
Sorry to disturbe you ,but I really read the README.md totaly,but I still do not know how to use ,because it will close quickly ,when I click the report.py,without any other tips ,so I think it must have something wrong,can you help me ?

**Comment by InfinityWei** [comment]
You need to first install python3 and add it to the environment variable PATH, and open cmd，follow the instruction and type command and enter to run the program

**Comment by TFboy1** [comment]
But when I get into cmd and open the python environment ,I input report.py ,it just show me"
`C:\Users\XXXX>python
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> report.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'report' is not defined. Did you mean: 'repr'?"`
why can't I enter it ?
