### ISSUE TITLE
推荐一下我的项目

### ISSUE THREAD

**Issue by lixiang810** [InfinityWei/NUIST_HealthyReport_NEW#6]
[我的项目](https://github.com/lixiang810/NUISTHealthReport)可以一次签完一个月。南信大的健康日报后端鉴权不完善，可以通过二次请求的方式覆写任何值，其中包括申请日期（因此没有每日签到的必要）。

（也许可以在 README 里加一下友链啥的？）

**Comment by InfinityWei** [comment]
你好，寒假期间有关注到您的项目，也非常感谢您的项目的部分代码（对WID的处理部分）对我的项目的启发，当然我写这个项目的初衷也是能够尽可能模拟真实的填报场景，确保不会露馅，和您的方式有些许不同。
友链已加，欢迎交换~

**Comment by lixiang810** [comment]
换上了（

**Comment by lixiang810** [comment]
另外欢迎来多火玩，nuist-go-out 的作者也在这里，还可以一起艹龙猫（已经可以跑了）
